apiVersion: v1
kind: Service
metadata:
  name: flask-aws-monitor-service
spec:
  type: LoadBalancer
  selector:
    app: flask-aws-monitor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
