
FROM python:3.9-slim AS builder

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

FROM python:3.9-slim

WORKDIR /app

COPY --from=builder /usr/local/lib/python3.9/site-packages/ /usr/local/lib/python3.9/site-packages/

COPY app.py .

ENV AWS_ACCESS_KEY_ID=""

ENV AWS_SECRET_ACCESS_KEY=""

EXPOSE 5001

CMD ["python", "app.py"]
